# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt1_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt1_nohuman_celuo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt1_nohuman_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt1_nohuman_noceluo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt3_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt3_nohuman_celuo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt3_nohuman_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt3_nohuman_noceluo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_human_celuo_weight_demp_avg/'  --save_dir 'output_vibf/model_gt5_human_celuo_weight_demp_avg_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_human_celuo_weight_demp_max/'  --save_dir 'output_vibf/model_gt5_human_celuo_weight_demp_max_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_human_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt5_human_celuo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_human_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt5_human_noceluo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_nohuman_celuo_weight_demp_avg/'  --save_dir 'output_vibf/model_gt5_nohuman_celuo_weight_demp_avg_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_nohuman_celuo_weight_demp_max/'  --save_dir 'output_vibf/model_gt5_nohuman_celuo_weight_demp_max_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt5_nohuman_celuo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_nohuman_noceluo_weight/'  --save_dir 'output_vibf/model_gt5_nohuman_noceluo_weight_sdnet/'
python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_random_celuo_weight_demp_avg/'  --save_dir 'output_vibf/model_gt5_random_celuo_weight_demp_avg_sdnet/'
python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_random_celuo_weight_demp_max/'  --save_dir 'output_vibf/model_gt5_random_celuo_weight_demp_max_sdnet/'
python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_random_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt5_random_celuo_weight_demp_sdnet/'
python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt5_random_noeluo_weight_demp/'  --save_dir 'output_vibf/model_gt5_random_noceluo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt7_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt7_nohuman_celuo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt7_nohuman_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt7_nohuman_noceluo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt9_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt9_nohuman_celuo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt9_nohuman_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt9_nohuman_noceluo_weight_demp_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt_yuanshi_celuo/'  --save_dir 'output_vibf/model_gt_yuanshi_celuo_sdnet/'
# python test_piliang.py --epoch 50 --checkpoint_dir 'model_gt_yuanshi_noceluo/'  --save_dir 'output_vibf/model_gt_yuanshi_noceluo_sdnet/'
# ###dataenhance


# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt1_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt1_nohuman_celuo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt1_nohuman_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt1_nohuman_noceluo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt3_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt3_nohuman_celuo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt3_nohuman_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt3_nohuman_noceluo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_human_celuo_weight_demp_avg/'  --save_dir 'output_vibf/model_gt5_human_celuo_weight_demp_avg_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_human_celuo_weight_demp_max/'  --save_dir 'output_vibf/model_gt5_human_celuo_weight_demp_max_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_human_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt5_human_celuo_weight_demp_dataenhance_sdnet_enhance'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_human_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt5_human_noceluo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_nohuman_celuo_weight_demp_avg/'  --save_dir 'output_vibf/model_gt5_nohuman_celuo_weight_demp_avg_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_nohuman_celuo_weight_demp_max/'  --save_dir 'output_vibf/model_gt5_nohuman_celuo_weight_demp_max_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt5_nohuman_celuo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_nohuman_noceluo_weight/'  --save_dir 'output_vibf/model_gt5_nohuman_noceluo_weight_sdnet_enhance/'
python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_random_celuo_weight_demp_avg/'  --save_dir 'output_vibf/model_gt5_random_celuo_weight_demp_avg_sdnet_enhance/'
python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_random_celuo_weight_demp_max/'  --save_dir 'output_vibf/model_gt5_random_celuo_weight_demp_max_sdnet_enhance/'
python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_random_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt5_random_celuo_weight_demp_dataenhance_sdnet_enhance/'
python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt5_random_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt5_random_noceluo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt7_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt7_nohuman_celuo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt7_nohuman_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt7_nohuman_noceluo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt9_nohuman_celuo_weight_demp/'  --save_dir 'output_vibf/model_gt9_nohuman_celuo_weight_demp_dataenhance_sdnet_enhance/'
# python test_piliang_dataenhance.py --epoch 50 --checkpoint_dir 'model_gt9_nohuman_noceluo_weight_demp/'  --save_dir 'output_vibf/model_gt9_nohuman_noceluo_weight_demp_dataenhance_sdnet_enhance/'